//ADDRESS OF PREVIOUS WHITELIST DAPP
const WHITELIST_CONTRACT_ADDRESS = "0x246482B920128770b25c4cAC03DA5E0248dB0449";
//URL TO EXTRACT METADATA FOR A CRYTP DEV NFT
const METADATA_URL = "https://nft-collection-iota-liart.vercel.app/api/";

module.exports = {WHITELIST_CONTRACT_ADDRESS , METADATA_URL};